//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iWindow.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iWindow.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Pappachan NC Connector.
        ///To start using enter the remote Ip address as well as the port in the textboxes provided and  select Connection&gt;&gt;Start.
        /// </summary>
        internal static string Introduction {
            get {
                return ResourceManager.GetString("Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] lastpacket {
            get {
                object obj = ResourceManager.GetObject("lastpacket", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] lastpacket_awl {
            get {
                object obj = ResourceManager.GetObject("lastpacket_awl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .@´.....C:\WinNC32\.....................................................................................................................................................C:\WINNC32\MILL105\.............................................................................................................................................MILL105..........................ÿÿ..................................................................................
        /// </summary>
        internal static string lastpacket_awl1 {
            get {
                return ResourceManager.GetString("lastpacket_awl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MILL105 {
            get {
                object obj = ResourceManager.GetObject("MILL105", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MILL105_ACC {
            get {
                object obj = ResourceManager.GetObject("MILL105_ACC", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Mill1051 {
            get {
                object obj = ResourceManager.GetObject("Mill1051", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MILL1052 {
            get {
                object obj = ResourceManager.GetObject("MILL1052", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MILL1053 {
            get {
                object obj = ResourceManager.GetObject("MILL1053", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] part11 {
            get {
                object obj = ResourceManager.GetObject("part11", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] part11_awl {
            get {
                object obj = ResourceManager.GetObject("part11_awl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Info]..Version=1.0..CheckChange=884cbd2e..FUNCTION FC 0 : VOID..NAME: WERKZEUGWENDER SIMULIEREN..BEGIN..NETWORK..UN  DB20.DBX  182.0..SPB M001..L   DB20.DBW   184..T   DB20.DBW   356..M001:NOP 0..NETWORK..L   DB20.DBW   184..L   W#16#1..&lt;I..U   DB20.DBX  182.0..=   M 125.1..NETWORK..L   DB20.DBW   184..L   W#16#63..&gt;I..U   DB20.DBX  182.0..=   M 125.2..NETWORK..O   M 125.1..O   M 125.2..S   DB3.DBX     0.0..U   DB1.DBX  1370.2..R   DB3.DBX     0.0..END_FUNCTION..FUNCTION FC 1 : VOID..NAME: INITIALISIERUNGE.
        /// </summary>
        internal static string part111 {
            get {
                return ResourceManager.GetString("part111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PCMASCH0 {
            get {
                object obj = ResourceManager.GetObject("PCMASCH0", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
